#!/bin/bash


if [ ! -e "/dev/box_1" ]; then
  zenity --error --text="雷达连接(前)失败，请检查雷达是否连接至上位机"
  exit 0
fi

if [ ! -e "/dev/box_2" ]; then
  zenity --error --text="雷达连接(后)失败，请检查雷达是否连接至上位机"
  exit 0
fi

source /opt/autolabor/ros/catkin_ws/devel/setup.bash
IP=`ifconfig wlan0 | grep "inet 地址:" | awk '{print $2}' | cut -c 8-`

if [ -z "$IP" ]; then
  IP="127.0.0.1"
fi

export ROS_MASTER_URI=http://$IP:11311/
export ROS_IP=$IP

nohup roslaunch autolabor_test_launch fslidar_test.launch&
sleep 5
zenity --info --text="遮挡雷达周围，如果发现画面有红点和白点，则雷达正常"
killall rosmaster


